global:
  tango_host: ska-low-csp-databaseds:10000
  cluster_domain: cluster.internal.dspsi
  exposeAllDS: true
  operator: true
  sub-system:
    ska-tango-base:
      enabled: false
  minikube: false

ska-low-station-beam-simulator:
  image:
    tag: 0.1.0-dev.cb9e5eaa5

  simulator:
    stationIds: [345, 431]
    substationId: 1
    destIp: 192.168.200.2
    sourceInterface: net1

  podAnnotations:
    k8s.v1.cni.cncf.io/networks: kube-system/cbf-sdp-1

ska-low-station-beam-simulator-tango:
  ska-tango-devices:
    deviceServerTypes:
      stationbeamsimulator:
        image:
          tag: 0.1.0-dev.cd5b5fd8e

    devices:
      StationBeamSimulator:
        testware/station-beam-simulator/345:
          station_id: 345
          substation_id: 1
          grpc_target: sbs-ska-low-station-beam-simulator-345:50051
        testware/station-beam-simulator/431:
          station_id: 431
          substation_id: 1
          grpc_target: sbs-ska-low-station-beam-simulator-431:50051

    deviceServers:
      stationbeamsimulator:
        stn-345:
          devices:
            StationBeamSimulator:
              - testware/station-beam-simulator/345
        stn-431:
          devices:
            StationBeamSimulator:
              - testware/station-beam-simulator/431

ska-tango-base:
  enabled: false
  deviceServersEnabled: false

ska-tango-tangogql-ariadne:
  enabled: false
  ska-tango-base:
    enabled: false

ska-tango-taranta:
  enabled: false
