# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import simulator_pb2 as simulator__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simulator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StationSimulatorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartScan = channel.unary_unary(
                '/simulator.v1.StationSimulator/StartScan',
                request_serializer=simulator__pb2.StartScanRequest.SerializeToString,
                response_deserializer=simulator__pb2.StartScanResponse.FromString,
                _registered_method=True)
        self.StopScan = channel.unary_unary(
                '/simulator.v1.StationSimulator/StopScan',
                request_serializer=simulator__pb2.StopScanRequest.SerializeToString,
                response_deserializer=simulator__pb2.StopScanResponse.FromString,
                _registered_method=True)
        self.PushDelayUpdate = channel.unary_unary(
                '/simulator.v1.StationSimulator/PushDelayUpdate',
                request_serializer=simulator__pb2.PushDelayUpdateRequest.SerializeToString,
                response_deserializer=simulator__pb2.PushDelayUpdateResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/simulator.v1.StationSimulator/GetStatus',
                request_serializer=simulator__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=simulator__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.WatchStatus = channel.unary_stream(
                '/simulator.v1.StationSimulator/WatchStatus',
                request_serializer=simulator__pb2.WatchStatusRequest.SerializeToString,
                response_deserializer=simulator__pb2.StatusResponse.FromString,
                _registered_method=True)


class StationSimulatorServicer:
    """Missing associated documentation comment in .proto file."""

    def StartScan(self, request, context):
        """Starts a scan. Fails if a scan is already running (call StopScan
        first) — matches simulator.py's StartScan.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopScan(self, request, context):
        """Stops the current scan, if any. Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushDelayUpdate(self, request, context):
        """Pushes a fresh delay polynomial for one named source. The caller
        (the Tango-facing side) is responsible for subscribing to CBF's
        delay-poly emulator attribute and forwarding every CHANGE_EVENT here
        — this process holds no Tango attribute subscriptions itself.
        source_id must match a tone source's source_id from the StartScan
        request that started the currently-running scan.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Point-in-time status — mirrors simulator.py's queue_depth attribute.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchStatus(self, request, context):
        """Server-streaming status: pushes a StatusResponse every
        update_interval_s until the caller cancels/disconnects. Prototype
        alternative to polling GetStatus once per Tango attribute (see
        docs/history.md's "one independent GetStatus RPC per attribute"
        note) — kept alongside GetStatus rather than replacing it, since a
        plain unary call is still the simpler shape for one-off checks
        (e.g. StartScan's already-running check) and ad hoc tooling.
        Independent of StartScan/StopScan/PushDelayUpdate: gRPC multiplexes
        RPCs on one channel, so those calls are never blocked by an open
        WatchStatus stream, and the stream is expected to live for as long
        as the caller wants updates -- e.g. the Tango device server's
        lifetime -- surviving across StartScan/StopScan calls rather than
        being scoped to one scan.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StationSimulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScan,
                    request_deserializer=simulator__pb2.StartScanRequest.FromString,
                    response_serializer=simulator__pb2.StartScanResponse.SerializeToString,
            ),
            'StopScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StopScan,
                    request_deserializer=simulator__pb2.StopScanRequest.FromString,
                    response_serializer=simulator__pb2.StopScanResponse.SerializeToString,
            ),
            'PushDelayUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PushDelayUpdate,
                    request_deserializer=simulator__pb2.PushDelayUpdateRequest.FromString,
                    response_serializer=simulator__pb2.PushDelayUpdateResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=simulator__pb2.GetStatusRequest.FromString,
                    response_serializer=simulator__pb2.StatusResponse.SerializeToString,
            ),
            'WatchStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchStatus,
                    request_deserializer=simulator__pb2.WatchStatusRequest.FromString,
                    response_serializer=simulator__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulator.v1.StationSimulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simulator.v1.StationSimulator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StationSimulator:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.v1.StationSimulator/StartScan',
            simulator__pb2.StartScanRequest.SerializeToString,
            simulator__pb2.StartScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.v1.StationSimulator/StopScan',
            simulator__pb2.StopScanRequest.SerializeToString,
            simulator__pb2.StopScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushDelayUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.v1.StationSimulator/PushDelayUpdate',
            simulator__pb2.PushDelayUpdateRequest.SerializeToString,
            simulator__pb2.PushDelayUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simulator.v1.StationSimulator/GetStatus',
            simulator__pb2.GetStatusRequest.SerializeToString,
            simulator__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/simulator.v1.StationSimulator/WatchStatus',
            simulator__pb2.WatchStatusRequest.SerializeToString,
            simulator__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
