// Sample control-plane API between a Tango device server (owns the
// Tango-facing bits: device properties, attribute subscriptions to CBF's
// delay-poly emulator) and this Go simulator process (owns signal
// generation + SPEAD/UDP sending). Mirrors simulator.py's StartScan/
// StopScan/queue_depth surface, plus PushDelayUpdate to forward delay
// polynomial updates the Tango side receives via CHANGE_EVENT
// subscriptions (this process has no Tango access of its own).
//
// Prototype scope: tone + noise sources only, no pulsar (see the Go
// prototype's README for why).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: simulator.proto

package simulatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StationSimulator_StartScan_FullMethodName       = "/simulator.v1.StationSimulator/StartScan"
	StationSimulator_StopScan_FullMethodName        = "/simulator.v1.StationSimulator/StopScan"
	StationSimulator_PushDelayUpdate_FullMethodName = "/simulator.v1.StationSimulator/PushDelayUpdate"
	StationSimulator_GetStatus_FullMethodName       = "/simulator.v1.StationSimulator/GetStatus"
	StationSimulator_WatchStatus_FullMethodName     = "/simulator.v1.StationSimulator/WatchStatus"
)

// StationSimulatorClient is the client API for StationSimulator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StationSimulatorClient interface {
	// Starts a scan. Fails if a scan is already running (call StopScan
	// first) — matches simulator.py's StartScan.
	StartScan(ctx context.Context, in *StartScanRequest, opts ...grpc.CallOption) (*StartScanResponse, error)
	// Stops the current scan, if any. Idempotent.
	StopScan(ctx context.Context, in *StopScanRequest, opts ...grpc.CallOption) (*StopScanResponse, error)
	// Pushes a fresh delay polynomial for one named source. The caller
	// (the Tango-facing side) is responsible for subscribing to CBF's
	// delay-poly emulator attribute and forwarding every CHANGE_EVENT here
	// — this process holds no Tango attribute subscriptions itself.
	// source_id must match a tone source's source_id from the StartScan
	// request that started the currently-running scan.
	PushDelayUpdate(ctx context.Context, in *PushDelayUpdateRequest, opts ...grpc.CallOption) (*PushDelayUpdateResponse, error)
	// Point-in-time status — mirrors simulator.py's queue_depth attribute.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Server-streaming status: pushes a StatusResponse every
	// update_interval_s until the caller cancels/disconnects. Prototype
	// alternative to polling GetStatus once per Tango attribute (see
	// docs/history.md's "one independent GetStatus RPC per attribute"
	// note) — kept alongside GetStatus rather than replacing it, since a
	// plain unary call is still the simpler shape for one-off checks
	// (e.g. StartScan's already-running check) and ad hoc tooling.
	// Independent of StartScan/StopScan/PushDelayUpdate: gRPC multiplexes
	// RPCs on one channel, so those calls are never blocked by an open
	// WatchStatus stream, and the stream is expected to live for as long
	// as the caller wants updates -- e.g. the Tango device server's
	// lifetime -- surviving across StartScan/StopScan calls rather than
	// being scoped to one scan.
	WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error)
}

type stationSimulatorClient struct {
	cc grpc.ClientConnInterface
}

func NewStationSimulatorClient(cc grpc.ClientConnInterface) StationSimulatorClient {
	return &stationSimulatorClient{cc}
}

func (c *stationSimulatorClient) StartScan(ctx context.Context, in *StartScanRequest, opts ...grpc.CallOption) (*StartScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartScanResponse)
	err := c.cc.Invoke(ctx, StationSimulator_StartScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationSimulatorClient) StopScan(ctx context.Context, in *StopScanRequest, opts ...grpc.CallOption) (*StopScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopScanResponse)
	err := c.cc.Invoke(ctx, StationSimulator_StopScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationSimulatorClient) PushDelayUpdate(ctx context.Context, in *PushDelayUpdateRequest, opts ...grpc.CallOption) (*PushDelayUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushDelayUpdateResponse)
	err := c.cc.Invoke(ctx, StationSimulator_PushDelayUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationSimulatorClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, StationSimulator_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stationSimulatorClient) WatchStatus(ctx context.Context, in *WatchStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StationSimulator_ServiceDesc.Streams[0], StationSimulator_WatchStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchStatusRequest, StatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StationSimulator_WatchStatusClient = grpc.ServerStreamingClient[StatusResponse]

// StationSimulatorServer is the server API for StationSimulator service.
// All implementations must embed UnimplementedStationSimulatorServer
// for forward compatibility.
type StationSimulatorServer interface {
	// Starts a scan. Fails if a scan is already running (call StopScan
	// first) — matches simulator.py's StartScan.
	StartScan(context.Context, *StartScanRequest) (*StartScanResponse, error)
	// Stops the current scan, if any. Idempotent.
	StopScan(context.Context, *StopScanRequest) (*StopScanResponse, error)
	// Pushes a fresh delay polynomial for one named source. The caller
	// (the Tango-facing side) is responsible for subscribing to CBF's
	// delay-poly emulator attribute and forwarding every CHANGE_EVENT here
	// — this process holds no Tango attribute subscriptions itself.
	// source_id must match a tone source's source_id from the StartScan
	// request that started the currently-running scan.
	PushDelayUpdate(context.Context, *PushDelayUpdateRequest) (*PushDelayUpdateResponse, error)
	// Point-in-time status — mirrors simulator.py's queue_depth attribute.
	GetStatus(context.Context, *GetStatusRequest) (*StatusResponse, error)
	// Server-streaming status: pushes a StatusResponse every
	// update_interval_s until the caller cancels/disconnects. Prototype
	// alternative to polling GetStatus once per Tango attribute (see
	// docs/history.md's "one independent GetStatus RPC per attribute"
	// note) — kept alongside GetStatus rather than replacing it, since a
	// plain unary call is still the simpler shape for one-off checks
	// (e.g. StartScan's already-running check) and ad hoc tooling.
	// Independent of StartScan/StopScan/PushDelayUpdate: gRPC multiplexes
	// RPCs on one channel, so those calls are never blocked by an open
	// WatchStatus stream, and the stream is expected to live for as long
	// as the caller wants updates -- e.g. the Tango device server's
	// lifetime -- surviving across StartScan/StopScan calls rather than
	// being scoped to one scan.
	WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[StatusResponse]) error
	mustEmbedUnimplementedStationSimulatorServer()
}

// UnimplementedStationSimulatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStationSimulatorServer struct{}

func (UnimplementedStationSimulatorServer) StartScan(context.Context, *StartScanRequest) (*StartScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartScan not implemented")
}
func (UnimplementedStationSimulatorServer) StopScan(context.Context, *StopScanRequest) (*StopScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopScan not implemented")
}
func (UnimplementedStationSimulatorServer) PushDelayUpdate(context.Context, *PushDelayUpdateRequest) (*PushDelayUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushDelayUpdate not implemented")
}
func (UnimplementedStationSimulatorServer) GetStatus(context.Context, *GetStatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedStationSimulatorServer) WatchStatus(*WatchStatusRequest, grpc.ServerStreamingServer[StatusResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchStatus not implemented")
}
func (UnimplementedStationSimulatorServer) mustEmbedUnimplementedStationSimulatorServer() {}
func (UnimplementedStationSimulatorServer) testEmbeddedByValue()                          {}

// UnsafeStationSimulatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StationSimulatorServer will
// result in compilation errors.
type UnsafeStationSimulatorServer interface {
	mustEmbedUnimplementedStationSimulatorServer()
}

func RegisterStationSimulatorServer(s grpc.ServiceRegistrar, srv StationSimulatorServer) {
	// If the following call panics, it indicates UnimplementedStationSimulatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StationSimulator_ServiceDesc, srv)
}

func _StationSimulator_StartScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSimulatorServer).StartScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StationSimulator_StartScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSimulatorServer).StartScan(ctx, req.(*StartScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StationSimulator_StopScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSimulatorServer).StopScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StationSimulator_StopScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSimulatorServer).StopScan(ctx, req.(*StopScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StationSimulator_PushDelayUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushDelayUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSimulatorServer).PushDelayUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StationSimulator_PushDelayUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSimulatorServer).PushDelayUpdate(ctx, req.(*PushDelayUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StationSimulator_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationSimulatorServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StationSimulator_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationSimulatorServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StationSimulator_WatchStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StationSimulatorServer).WatchStatus(m, &grpc.GenericServerStream[WatchStatusRequest, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StationSimulator_WatchStatusServer = grpc.ServerStreamingServer[StatusResponse]

// StationSimulator_ServiceDesc is the grpc.ServiceDesc for StationSimulator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StationSimulator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simulator.v1.StationSimulator",
	HandlerType: (*StationSimulatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartScan",
			Handler:    _StationSimulator_StartScan_Handler,
		},
		{
			MethodName: "StopScan",
			Handler:    _StationSimulator_StopScan_Handler,
		},
		{
			MethodName: "PushDelayUpdate",
			Handler:    _StationSimulator_PushDelayUpdate_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _StationSimulator_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchStatus",
			Handler:       _StationSimulator_WatchStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "simulator.proto",
}
