// Sample control-plane API between a Tango device server (owns the
// Tango-facing bits: device properties, attribute subscriptions to CBF's
// delay-poly emulator) and this Go simulator process (owns signal
// generation + SPEAD/UDP sending). Mirrors simulator.py's StartScan/
// StopScan/queue_depth surface, plus PushDelayUpdate to forward delay
// polynomial updates the Tango side receives via CHANGE_EVENT
// subscriptions (this process has no Tango access of its own).
//
// Prototype scope: tone + noise sources only, no pulsar (see the Go
// prototype's README for why).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: simulator.proto

package simulatorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Per ska-low-csp-delaymodel/1.0 (ADR-88 in ska-telmodel) — see
// common.DelayPolynomial in the Python codebase.
type DelayPolynomial struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StationId         int32                  `protobuf:"varint,1,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	StartValiditySec  float64                `protobuf:"fixed64,2,opt,name=start_validity_sec,json=startValiditySec,proto3" json:"start_validity_sec,omitempty"`
	ValidityPeriodSec float64                `protobuf:"fixed64,3,opt,name=validity_period_sec,json=validityPeriodSec,proto3" json:"validity_period_sec,omitempty"`
	XypolCoeffsNs     []float64              `protobuf:"fixed64,4,rep,packed,name=xypol_coeffs_ns,json=xypolCoeffsNs,proto3" json:"xypol_coeffs_ns,omitempty"`
	YpolOffsetNs      float64                `protobuf:"fixed64,5,opt,name=ypol_offset_ns,json=ypolOffsetNs,proto3" json:"ypol_offset_ns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DelayPolynomial) Reset() {
	*x = DelayPolynomial{}
	mi := &file_simulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayPolynomial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayPolynomial) ProtoMessage() {}

func (x *DelayPolynomial) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayPolynomial.ProtoReflect.Descriptor instead.
func (*DelayPolynomial) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{0}
}

func (x *DelayPolynomial) GetStationId() int32 {
	if x != nil {
		return x.StationId
	}
	return 0
}

func (x *DelayPolynomial) GetStartValiditySec() float64 {
	if x != nil {
		return x.StartValiditySec
	}
	return 0
}

func (x *DelayPolynomial) GetValidityPeriodSec() float64 {
	if x != nil {
		return x.ValidityPeriodSec
	}
	return 0
}

func (x *DelayPolynomial) GetXypolCoeffsNs() []float64 {
	if x != nil {
		return x.XypolCoeffsNs
	}
	return nil
}

func (x *DelayPolynomial) GetYpolOffsetNs() float64 {
	if x != nil {
		return x.YpolOffsetNs
	}
	return 0
}

// A tone source. source_id is this process's own handle for routing
// PushDelayUpdate calls to the right DelayFeed — it never goes on the
// wire to CBF.
type ToneSourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	FreqHz        float64                `protobuf:"fixed64,2,opt,name=freq_hz,json=freqHz,proto3" json:"freq_hz,omitempty"`
	Amplitude     float64                `protobuf:"fixed64,3,opt,name=amplitude,proto3" json:"amplitude,omitempty"` // defaults to 1.0 if unset (0 is treated as unset)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToneSourceConfig) Reset() {
	*x = ToneSourceConfig{}
	mi := &file_simulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToneSourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToneSourceConfig) ProtoMessage() {}

func (x *ToneSourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToneSourceConfig.ProtoReflect.Descriptor instead.
func (*ToneSourceConfig) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{1}
}

func (x *ToneSourceConfig) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ToneSourceConfig) GetFreqHz() float64 {
	if x != nil {
		return x.FreqHz
	}
	return 0
}

func (x *ToneSourceConfig) GetAmplitude() float64 {
	if x != nil {
		return x.Amplitude
	}
	return 0
}

type NoiseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Std           float64                `protobuf:"fixed64,1,opt,name=std,proto3" json:"std,omitempty"`
	Seed          int64                  `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoiseConfig) Reset() {
	*x = NoiseConfig{}
	mi := &file_simulator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseConfig) ProtoMessage() {}

func (x *NoiseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseConfig.ProtoReflect.Descriptor instead.
func (*NoiseConfig) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{2}
}

func (x *NoiseConfig) GetStd() float64 {
	if x != nil {
		return x.Std
	}
	return 0
}

func (x *NoiseConfig) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type StartScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObsTimeEpochS float64                `protobuf:"fixed64,1,opt,name=obs_time_epoch_s,json=obsTimeEpochS,proto3" json:"obs_time_epoch_s,omitempty"`
	ScanDurationS float64                `protobuf:"fixed64,2,opt,name=scan_duration_s,json=scanDurationS,proto3" json:"scan_duration_s,omitempty"`
	ScanId        int64                  `protobuf:"varint,3,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	SubarrayId    int32                  `protobuf:"varint,4,opt,name=subarray_id,json=subarrayId,proto3" json:"subarray_id,omitempty"`
	BeamId        int32                  `protobuf:"varint,5,opt,name=beam_id,json=beamId,proto3" json:"beam_id,omitempty"`
	NumChannels   int32                  `protobuf:"varint,6,opt,name=num_channels,json=numChannels,proto3" json:"num_channels,omitempty"` // 0 means "use MaxNumChannels (384)"
	ToneSources   []*ToneSourceConfig    `protobuf:"bytes,7,rep,name=tone_sources,json=toneSources,proto3" json:"tone_sources,omitempty"`
	Noise         *NoiseConfig           `protobuf:"bytes,8,opt,name=noise,proto3" json:"noise,omitempty"` // omit entirely for no noise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScanRequest) Reset() {
	*x = StartScanRequest{}
	mi := &file_simulator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScanRequest) ProtoMessage() {}

func (x *StartScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScanRequest.ProtoReflect.Descriptor instead.
func (*StartScanRequest) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{3}
}

func (x *StartScanRequest) GetObsTimeEpochS() float64 {
	if x != nil {
		return x.ObsTimeEpochS
	}
	return 0
}

func (x *StartScanRequest) GetScanDurationS() float64 {
	if x != nil {
		return x.ScanDurationS
	}
	return 0
}

func (x *StartScanRequest) GetScanId() int64 {
	if x != nil {
		return x.ScanId
	}
	return 0
}

func (x *StartScanRequest) GetSubarrayId() int32 {
	if x != nil {
		return x.SubarrayId
	}
	return 0
}

func (x *StartScanRequest) GetBeamId() int32 {
	if x != nil {
		return x.BeamId
	}
	return 0
}

func (x *StartScanRequest) GetNumChannels() int32 {
	if x != nil {
		return x.NumChannels
	}
	return 0
}

func (x *StartScanRequest) GetToneSources() []*ToneSourceConfig {
	if x != nil {
		return x.ToneSources
	}
	return nil
}

func (x *StartScanRequest) GetNoise() *NoiseConfig {
	if x != nil {
		return x.Noise
	}
	return nil
}

type StartScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartScanResponse) Reset() {
	*x = StartScanResponse{}
	mi := &file_simulator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartScanResponse) ProtoMessage() {}

func (x *StartScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartScanResponse.ProtoReflect.Descriptor instead.
func (*StartScanResponse) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{4}
}

func (x *StartScanResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartScanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopScanRequest) Reset() {
	*x = StopScanRequest{}
	mi := &file_simulator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopScanRequest) ProtoMessage() {}

func (x *StopScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopScanRequest.ProtoReflect.Descriptor instead.
func (*StopScanRequest) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{5}
}

type StopScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopScanResponse) Reset() {
	*x = StopScanResponse{}
	mi := &file_simulator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopScanResponse) ProtoMessage() {}

func (x *StopScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopScanResponse.ProtoReflect.Descriptor instead.
func (*StopScanResponse) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{6}
}

func (x *StopScanResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PushDelayUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Polynomial    *DelayPolynomial       `protobuf:"bytes,2,opt,name=polynomial,proto3" json:"polynomial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDelayUpdateRequest) Reset() {
	*x = PushDelayUpdateRequest{}
	mi := &file_simulator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDelayUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDelayUpdateRequest) ProtoMessage() {}

func (x *PushDelayUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDelayUpdateRequest.ProtoReflect.Descriptor instead.
func (*PushDelayUpdateRequest) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{7}
}

func (x *PushDelayUpdateRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PushDelayUpdateRequest) GetPolynomial() *DelayPolynomial {
	if x != nil {
		return x.Polynomial
	}
	return nil
}

type PushDelayUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushDelayUpdateResponse) Reset() {
	*x = PushDelayUpdateResponse{}
	mi := &file_simulator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDelayUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDelayUpdateResponse) ProtoMessage() {}

func (x *PushDelayUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDelayUpdateResponse.ProtoReflect.Descriptor instead.
func (*PushDelayUpdateResponse) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{8}
}

func (x *PushDelayUpdateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_simulator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{9}
}

type StatusResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ScanRunning bool                   `protobuf:"varint,1,opt,name=scan_running,json=scanRunning,proto3" json:"scan_running,omitempty"`
	QueueDepth  int32                  `protobuf:"varint,2,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	// Pacing drift at the most recent tick: wall-clock time minus that
	// tick's target time, in seconds. Positive means the producer is
	// running behind its real-time schedule (see ScanRunner's
	// OverrunTolerance-gated log line, which this mirrors as a queryable
	// value); zero or negative means on-pace or ahead. 0 if no scan has
	// produced a tick yet.
	DriftSeconds float64 `protobuf:"fixed64,3,opt,name=drift_seconds,json=driftSeconds,proto3" json:"drift_seconds,omitempty"`
	// The most recently produced tick's index (0-based) within the
	// current scan. 0 if no scan has produced a tick yet.
	TickNumber    int64 `protobuf:"varint,4,opt,name=tick_number,json=tickNumber,proto3" json:"tick_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_simulator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_simulator_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetScanRunning() bool {
	if x != nil {
		return x.ScanRunning
	}
	return false
}

func (x *StatusResponse) GetQueueDepth() int32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *StatusResponse) GetDriftSeconds() float64 {
	if x != nil {
		return x.DriftSeconds
	}
	return 0
}

func (x *StatusResponse) GetTickNumber() int64 {
	if x != nil {
		return x.TickNumber
	}
	return 0
}

var File_simulator_proto protoreflect.FileDescriptor

const file_simulator_proto_rawDesc = "" +
	"\n" +
	"\x0fsimulator.proto\x12\fsimulator.v1\"\xdc\x01\n" +
	"\x0fDelayPolynomial\x12\x1d\n" +
	"\n" +
	"station_id\x18\x01 \x01(\x05R\tstationId\x12,\n" +
	"\x12start_validity_sec\x18\x02 \x01(\x01R\x10startValiditySec\x12.\n" +
	"\x13validity_period_sec\x18\x03 \x01(\x01R\x11validityPeriodSec\x12&\n" +
	"\x0fxypol_coeffs_ns\x18\x04 \x03(\x01R\rxypolCoeffsNs\x12$\n" +
	"\x0eypol_offset_ns\x18\x05 \x01(\x01R\fypolOffsetNs\"f\n" +
	"\x10ToneSourceConfig\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x17\n" +
	"\afreq_hz\x18\x02 \x01(\x01R\x06freqHz\x12\x1c\n" +
	"\tamplitude\x18\x03 \x01(\x01R\tamplitude\"3\n" +
	"\vNoiseConfig\x12\x10\n" +
	"\x03std\x18\x01 \x01(\x01R\x03std\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\x03R\x04seed\"\xcd\x02\n" +
	"\x10StartScanRequest\x12'\n" +
	"\x10obs_time_epoch_s\x18\x01 \x01(\x01R\robsTimeEpochS\x12&\n" +
	"\x0fscan_duration_s\x18\x02 \x01(\x01R\rscanDurationS\x12\x17\n" +
	"\ascan_id\x18\x03 \x01(\x03R\x06scanId\x12\x1f\n" +
	"\vsubarray_id\x18\x04 \x01(\x05R\n" +
	"subarrayId\x12\x17\n" +
	"\abeam_id\x18\x05 \x01(\x05R\x06beamId\x12!\n" +
	"\fnum_channels\x18\x06 \x01(\x05R\vnumChannels\x12A\n" +
	"\ftone_sources\x18\a \x03(\v2\x1e.simulator.v1.ToneSourceConfigR\vtoneSources\x12/\n" +
	"\x05noise\x18\b \x01(\v2\x19.simulator.v1.NoiseConfigR\x05noise\"=\n" +
	"\x11StartScanResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fStopScanRequest\"\"\n" +
	"\x10StopScanResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"t\n" +
	"\x16PushDelayUpdateRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12=\n" +
	"\n" +
	"polynomial\x18\x02 \x01(\v2\x1d.simulator.v1.DelayPolynomialR\n" +
	"polynomial\")\n" +
	"\x17PushDelayUpdateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x12\n" +
	"\x10GetStatusRequest\"\x9a\x01\n" +
	"\x0eStatusResponse\x12!\n" +
	"\fscan_running\x18\x01 \x01(\bR\vscanRunning\x12\x1f\n" +
	"\vqueue_depth\x18\x02 \x01(\x05R\n" +
	"queueDepth\x12#\n" +
	"\rdrift_seconds\x18\x03 \x01(\x01R\fdriftSeconds\x12\x1f\n" +
	"\vtick_number\x18\x04 \x01(\x03R\n" +
	"tickNumber2\xd6\x02\n" +
	"\x10StationSimulator\x12L\n" +
	"\tStartScan\x12\x1e.simulator.v1.StartScanRequest\x1a\x1f.simulator.v1.StartScanResponse\x12I\n" +
	"\bStopScan\x12\x1d.simulator.v1.StopScanRequest\x1a\x1e.simulator.v1.StopScanResponse\x12^\n" +
	"\x0fPushDelayUpdate\x12$.simulator.v1.PushDelayUpdateRequest\x1a%.simulator.v1.PushDelayUpdateResponse\x12I\n" +
	"\tGetStatus\x12\x1e.simulator.v1.GetStatusRequest\x1a\x1c.simulator.v1.StatusResponseB;Z9github.com/skao/station-beam-simulator-go/api/simulatorpbb\x06proto3"

var (
	file_simulator_proto_rawDescOnce sync.Once
	file_simulator_proto_rawDescData []byte
)

func file_simulator_proto_rawDescGZIP() []byte {
	file_simulator_proto_rawDescOnce.Do(func() {
		file_simulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulator_proto_rawDesc), len(file_simulator_proto_rawDesc)))
	})
	return file_simulator_proto_rawDescData
}

var file_simulator_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_simulator_proto_goTypes = []any{
	(*DelayPolynomial)(nil),         // 0: simulator.v1.DelayPolynomial
	(*ToneSourceConfig)(nil),        // 1: simulator.v1.ToneSourceConfig
	(*NoiseConfig)(nil),             // 2: simulator.v1.NoiseConfig
	(*StartScanRequest)(nil),        // 3: simulator.v1.StartScanRequest
	(*StartScanResponse)(nil),       // 4: simulator.v1.StartScanResponse
	(*StopScanRequest)(nil),         // 5: simulator.v1.StopScanRequest
	(*StopScanResponse)(nil),        // 6: simulator.v1.StopScanResponse
	(*PushDelayUpdateRequest)(nil),  // 7: simulator.v1.PushDelayUpdateRequest
	(*PushDelayUpdateResponse)(nil), // 8: simulator.v1.PushDelayUpdateResponse
	(*GetStatusRequest)(nil),        // 9: simulator.v1.GetStatusRequest
	(*StatusResponse)(nil),          // 10: simulator.v1.StatusResponse
}
var file_simulator_proto_depIdxs = []int32{
	1,  // 0: simulator.v1.StartScanRequest.tone_sources:type_name -> simulator.v1.ToneSourceConfig
	2,  // 1: simulator.v1.StartScanRequest.noise:type_name -> simulator.v1.NoiseConfig
	0,  // 2: simulator.v1.PushDelayUpdateRequest.polynomial:type_name -> simulator.v1.DelayPolynomial
	3,  // 3: simulator.v1.StationSimulator.StartScan:input_type -> simulator.v1.StartScanRequest
	5,  // 4: simulator.v1.StationSimulator.StopScan:input_type -> simulator.v1.StopScanRequest
	7,  // 5: simulator.v1.StationSimulator.PushDelayUpdate:input_type -> simulator.v1.PushDelayUpdateRequest
	9,  // 6: simulator.v1.StationSimulator.GetStatus:input_type -> simulator.v1.GetStatusRequest
	4,  // 7: simulator.v1.StationSimulator.StartScan:output_type -> simulator.v1.StartScanResponse
	6,  // 8: simulator.v1.StationSimulator.StopScan:output_type -> simulator.v1.StopScanResponse
	8,  // 9: simulator.v1.StationSimulator.PushDelayUpdate:output_type -> simulator.v1.PushDelayUpdateResponse
	10, // 10: simulator.v1.StationSimulator.GetStatus:output_type -> simulator.v1.StatusResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_simulator_proto_init() }
func file_simulator_proto_init() {
	if File_simulator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulator_proto_rawDesc), len(file_simulator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simulator_proto_goTypes,
		DependencyIndexes: file_simulator_proto_depIdxs,
		MessageInfos:      file_simulator_proto_msgTypes,
	}.Build()
	File_simulator_proto = out.File
	file_simulator_proto_goTypes = nil
	file_simulator_proto_depIdxs = nil
}
